### ISSUE TITLE
LCD screen installation problem

### ISSUE THREAD

**Issue by aGGreSSiv** [domschl/RaspberryNtpServer#8]
> @aGGreSSiv : I've updated the documentation of the install process. If you are still having trouble, please open a new issue and describe at what step you're stuck, and we have a look at it!

I connected remotely and followed the steps one by one according to the instructions. First I updated the operating system, then I entered the commands one by one. None of the commands gave an error. The LCD is not plugged in right now, maybe that's why it gives an error, but when I check the chronotron service status to check, it gives the following output.

```
pi@raspberrypi:~ $ sudo systemctl status chronotron
● chronotron.service - Display chrony statistics on 4x20 LCD
     Loaded: loaded (/etc/systemd/system/chronotron.service; enabled; vendor preset: enabled)
     Active: failed (Result: exit-code) since Thu 2023-12-21 13:22:11 +03; 11s ago
    Process: 537 ExecStart=/opt/chronotron/bin/python /opt/chronotron/chronotron.py (code=exited, status=1/FAILURE)
   Main PID: 537 (code=exited, status=1/FAILURE)
        CPU: 422ms

Dec 21 13:22:11 raspberrypi python[537]: Traceback (most recent call last):
Dec 21 13:22:11 raspberrypi python[537]:   File "/opt/chronotron/chronotron.py", line 237, in <module>
Dec 21 13:22:11 raspberrypi python[537]:     main_loop()
Dec 21 13:22:11 raspberrypi python[537]:   File "/opt/chronotron/chronotron.py", line 151, in main_loop
Dec 21 13:22:11 raspberrypi python[537]:     lcd = LcdDisplay()
Dec 21 13:22:11 raspberrypi python[537]:   File "/opt/chronotron/i2c_lcd.py", line 8, in __init__
Dec 21 13:22:11 raspberrypi python[537]:     self.bus = smbus.SMBus(sm_bus)  # Rev 1 Pi: 0, Rev 2 Pi: 1
Dec 21 13:22:11 raspberrypi python[537]: FileNotFoundError: [Errno 2] No such file or directory
Dec 21 13:22:11 raspberrypi systemd[1]: chronotron.service: Main process exited, code=exited, status=1/FAILURE
Dec 21 13:22:11 raspberrypi systemd[1]: chronotron.service: Failed with result 'exit-code'.

```
![image](https://github.com/domschl/RaspberryNtpServer/assets/5939750/99167226-6186-44b9-9af2-7cd6596d2c7f)

**Comment by domschl** [comment]
You need to install `smbus` within the python virtual environment:

```bash
cd /opt/chronotron
source bin/activate
pip install smbus
```

then restart the chronotron service.

**Comment by domschl** [comment]
Also, make sure that I2C is active: `sudo raspi-config`, select "Interface options", and make sure that I2C is enabled.

You can verify with: `i2cdetect 1`

It should show something like:

```
WARNING! This program can confuse your I2C bus, cause data loss and worse!
I will probe file /dev/i2c-1.
I will probe address range 0x08-0x77.
Continue? [Y/n] 
     0  1  2  3  4  5  6  7  8  9  a  b  c  d  e  f
00:                         -- -- -- -- -- -- -- -- 
10: -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- 
20: -- -- -- -- -- -- -- 27 -- -- -- -- -- -- -- -- 
30: -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- 
40: -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- 
50: -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- 
60: -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- 
70: -- -- -- -- -- -- -- --      
```

That `27` should appear, if your display is connected correctly!

**Comment by aGGreSSiv** [comment]
I2c Activated 

```
pi@raspberrypi:~ $ i2cdetect 1
WARNING! This program can confuse your I2C bus, cause data loss and worse!
I will probe file /dev/i2c-1.
I will probe address range 0x08-0x77.
Continue? [Y/n] y
     0  1  2  3  4  5  6  7  8  9  a  b  c  d  e  f
00:                         -- -- -- -- -- -- -- --
10: -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- --
20: -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- --
30: -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- --
40: -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- --
50: -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- --
60: -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- --
70: -- -- -- -- -- -- -- --

```
smbus İnstalled;
```
(chronotron) pi@raspberrypi:/opt/chronotron $ sudo pip install smbus
Looking in indexes: https://pypi.org/simple, https://www.piwheels.org/simple
Collecting smbus
  Downloading smbus-1.1.post2.tar.gz (104 kB)
     |████████████████████████████████| 104 kB 1.1 MB/s
Building wheels for collected packages: smbus
  Building wheel for smbus (setup.py) ... done
  Created wheel for smbus: filename=smbus-1.1.post2-cp39-cp39-linux_aarch64.whl size=40622 sha256=9634b265a325d0c514b1a243e0f9d3c8df653fb0ea80daabe45f60db23716c34
  Stored in directory: /root/.cache/pip/wheels/27/6b/5f/d61caec49a6f3347a083b3e43fa397c353e086e081029f174d
Successfully built smbus
Installing collected packages: smbus
Successfully installed smbus-1.1.post2

```


but the result did not change;
```
pi@raspberrypi:~ $ sudo systemctl status chronotron
● chronotron.service - Display chrony statistics on 4x20 LCD
     Loaded: loaded (/etc/systemd/system/chronotron.service; enabled; vendor preset: enabled)
     Active: failed (Result: exit-code) since Thu 2023-12-21 15:21:16 +03; 51s ago
    Process: 491 ExecStart=/opt/chronotron/bin/python /opt/chronotron/chronotron.py (code=exited, status=1/FAILURE)
   Main PID: 491 (code=exited, status=1/FAILURE)
        CPU: 445ms

Dec 21 15:21:16 raspberrypi python[491]:     main_loop()
Dec 21 15:21:16 raspberrypi python[491]:   File "/opt/chronotron/chronotron.py", line 151, in main_loop
Dec 21 15:21:16 raspberrypi python[491]:     lcd = LcdDisplay()
Dec 21 15:21:16 raspberrypi python[491]:   File "/opt/chronotron/i2c_lcd.py", line 21, in __init__
Dec 21 15:21:16 raspberrypi python[491]:     self.write(0x33, self.type_command)  # init sequence: 0x03, 0x03
Dec 21 15:21:16 raspberrypi python[491]:   File "/opt/chronotron/i2c_lcd.py", line 45, in write
Dec 21 15:21:16 raspberrypi python[491]:     self.bus.write_byte(self.i2c_addr, hi_byte)
Dec 21 15:21:16 raspberrypi python[491]: OSError: [Errno 5] Input/output error
Dec 21 15:21:16 raspberrypi systemd[1]: chronotron.service: Main process exited, code=exited, status=1/FAILURE
Dec 21 15:21:16 raspberrypi systemd[1]: chronotron.service: Failed with result 'exit-code'.

```

Could the problem be related to the LCD Screen not being installed yet? I'll connect it when I get home this evening.

**Comment by domschl** [comment]
The HD44780 display is not visible on the I2C bus. The possible causes are:

- electric connection not working (four cables need to be correctly connected)
- You have a Raspberry Pi Gen 1 (the very old first model)? (verify with `i2cdetect 0` if the other bus is used.)

`i2cdetect 1` should detect the `27` as active, if the display is correctly connected. This is completely independent of any Chronotron software.

As for the display driver: it's implemented in python in "i2c_lcd.py", so no extra software is needed.

**Comment by aGGreSSiv** [comment]
Ok. I'll plug in the screen and try it tonight. As I said, I installed apps by accessing the Pi remotely. I will share the result.

**Comment by domschl** [comment]
Sorry I missed that!

I've updated the code to give proper diagnostics for missing displays. It would now log:

```
Dec 21 14:37:30 chronotron systemd[1]: Started chronotron.service - Display chrony statistics on 4x20 LCD.
Dec 21 14:37:30 chronotron python[39157]: INFO:Chronotron:Chronotron version 2.0.0 starting
Dec 21 14:37:30 chronotron python[39157]: ERROR:LcdDisplay:Cannot open LCD on I2C bus: [Errno 2] No such file or directory
Dec 21 14:37:30 chronotron python[39157]: ERROR:Chronotron:Failed to open display, exiting...
Dec 21 14:37:30 chronotron systemd[1]: chronotron.service: Main process exited, code=exited, status=255/EXCEPTION
Dec 21 14:37:30 chronotron systemd[1]: chronotron.service: Failed with result 'exit-code'.
```

**Comment by aGGreSSiv** [comment]
Yes, LCD is visible now
```
pi@raspberrypi:~ $ sudo i2cdetect 1
WARNING! This program can confuse your I2C bus, cause data loss and worse!
I will probe file /dev/i2c-1.
I will probe address range 0x08-0x77.
Continue? [Y/n] y
     0  1  2  3  4  5  6  7  8  9  a  b  c  d  e  f
00:                         -- -- -- -- -- -- -- --
10: -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- --
20: -- -- -- -- -- -- -- 27 -- -- -- -- -- -- -- --
30: -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- --
40: -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- --
50: -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- --
60: -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- --
70: -- -- -- -- -- -- -- --

```
chronotron service also works properly;
```
pi@raspberrypi:~ $ sudo systemctl status chronotron
● chronotron.service - Display chrony statistics on 4x20 LCD
     Loaded: loaded (/etc/systemd/system/chronotron.service; enabled; vendor preset: enabled)
     Active: active (running) since Thu 2023-12-21 19:19:56 +03; 1min 47s ago
   Main PID: 507 (python)
      Tasks: 1 (limit: 779)
        CPU: 7.686s
     CGroup: /system.slice/chronotron.service
             └─507 /opt/chronotron/bin/python /opt/chronotron/chronotron.py

Dec 21 19:19:56 raspberrypi systemd[1]: Started Display chrony statistics on 4x20 LCD.
Dec 21 19:19:59 raspberrypi python[507]: INFO:Chronotron:Chronotron version 2.0.0 starting
Dec 21 19:20:00 raspberrypi python[507]: INFO:Chronotron:Chrony stratum level changed to 1
Dec 21 19:20:43 raspberrypi python[507]: INFO:Chronotron:Chrony aquired lock to time source
Dec 21 19:20:43 raspberrypi python[507]: INFO:Chronotron:Chrony receiving time source from time.ume.tubitak.g>
Dec 21 19:20:43 raspberrypi python[507]: INFO:Chronotron:Chrony stratum level changed to 2
Dec 21 19:21:26 raspberrypi python[507]: INFO:Chronotron:Chrony receiving time source from PPS
Dec 21 19:21:26 raspberrypi python[507]: INFO:Chronotron:Chrony locked to high precision GPS PPS signal
Dec 21 19:21:27 raspberrypi python[507]: INFO:Chronotron:Chrony stratum level changed to 1
```
But I don't see anything except the backlight of the screen is on. Since I see the I2C address, there is no problem with the connection.

I did the installation via [this site ](https://blog.networkprofile.org/gps-backed-local-ntp-server/)before seeing your post. But later, when I wanted to add a screen and looked at your NTP server instructions, I saw that they were identical. However, the reason why there is no image on the screen may be something I missed.

Since I'm not a software developer and I don't know much about Linux, I might be wasting your time with something stupid.

**Comment by aGGreSSiv** [comment]
Yes, I forgot to do the stupid little thing. It came to mind as soon as I pressed enter after my last post. There was a small potentiometer behind these screens, right? :)

Thanks for your help, everything is working as it should now.

**Comment by domschl** [comment]
Excellent. I close this then.
